name: CI for C++ and Arduino Uno

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  cpp-arduino-build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download Arduino CLI
        uses: arduino/setup-arduino-cli@v1
        with:
          version: '0.19.2'

      - name: Download CMake
        run: choco install cmake

      - name: Download platform Arduino AVR
        run: arduino-cli core install arduino:avr

      - name: Config CMake
        run: cmake -S . -B build
        shell: cmd

      - name: Build with CMake
        run: cmake --build build
        shell: cmd
      
      - name: Download build artefacts
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts
          path: build/*